### ISSUE TITLE
Error when selecting Update in Change Log

### ISSUE THREAD

**Issue by joemcl** [eileenmcnaughton/nz.co.fuzion.extendedloggingreports#2]
Hey Eileen - I'm getting this error when selecting Update in a Change Log record. We're on Civi 4.6.16 and version 1.0 of the Extended Logging extension.

![20160512extendedloggingerror](https://cloud.githubusercontent.com/assets/3912434/15224885/bad8b7ca-1849-11e6-8414-b93f37759081.png)

**Comment by eileenmcnaughton** [comment]
Hmm I did that extension ages ago - I guess it has contributionType not financialType (shows how long ago).

Do you know what this extension does that core reports don't do?

**Comment by joemcl** [comment]
Hey thanks for the update Eileen. Will install it tonight. I'm not sure what it does that core reports don't - but I do know that the Change Log tab/report for an individual record is handy to have when looking at Summary, Contributions etc for an individual. I ran Change Log and clicked on Update to try to figure out/remember what I had changed last week for a particular record.

**Comment by eileenmcnaughton** [comment]
OK - I need to put out a blog about changes to logging recently introduced to 4.7 too....

**Comment by joemcl** [comment]
Cool, looking forward to it.
